src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @Vich\Uploadable()
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    #[Assert\NotBlank]
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    #[Assert\NotBlank]
    private $body;

    /**
     * @ORM\Column(type="datetime")
     */
    #[Assert\NotBlank]
    #[Assert\GreaterThan('today')]
    private $publish_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="article_image", fileNameProperty="image")
     */
    #[Assert\Image]
    private $imageFile;

    /**
     * @ORM\Column (type="datetime")
     */
    private $updatedAt;

    public function __construct()
    {
        $this->updatedAt = new \DateTime();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return $this
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getBody(): ?string
    {
        return $this->body;
    }

    /**
     * @param string $body
     * @return $this
     */
    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getPublishAt(): ?\DateTimeInterface
    {
        return $this->publish_at;
    }

    /**
     * @param \DateTimeInterface $publish_at
     * @return $this
     */
    public function setPublishAt(\DateTimeInterface $publish_at): self
    {
        $this->publish_at = $publish_at;

        return $this;
    }

    /**
     * @param File|null $image
     * @return void
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            $this->updatedAt = new \DateTime();
        }
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @return string|null
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @param string|null $image
     * @return $this
     */
    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTimeInterface $updatedAt
     * @return $this
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ArticleType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class,
                [
                    'attr' => ['class' => 'form-control'],
                ])
            ->add('body', TextareaType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('publish_at', DateTimeType::class, [
                'placeholder' => [
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day',
                ],
                ])
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'mapped' => 'image',
                'constraints' => [
                new Image(['maxSize' => '2048k'])
                ],
                'attr' => ['class' => 'form-control']
                ])
            ->add('submit', SubmitType::class,
                [
                    'attr' => ['class' => 'btn btn-outline-info mt-2']
                ]);
    }

    /**
     * @param OptionsResolver $resolver
     * @return void
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Event\ArticleCreateEvent;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use DOMDocument;
use DOMXPath;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

class ArticleController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    private EntityManagerInterface $entityManager;

    /**
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @param Environment $twig
     * @param ArticleRepository $articleRepository
     * @return Response
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     * @Route ("/", name="homepage")
     */
    public function index(Environment $twig, ArticleRepository $articleRepository): Response
    {
        return new Response($twig->render('article/index.html.twig',
            [
                'articles' => $articleRepository->findAll(),
                'exchange_rates' => $this->getExchangeRates(),
            ]));
    }

    /**
     * @param Environment $twig
     * @param ArticleRepository $articleRepository
     * @param $id
     * @return Response
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     * @Route ("/article/{id}", name="article.show")
     */
    public function show(Environment $twig, ArticleRepository $articleRepository, $id): Response
    {
        return new Response($twig->render('article/show.html.twig', [
            'article' => $articleRepository->find($id),
        ]));
    }

    /**
     * @param Request $request
     * @param Environment $twig
     * @param EventDispatcherInterface $dispatcher
     * @return RedirectResponse|Response
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     * @Route ("/create", name="article.create")
     */
    public function create(Request $request, Environment $twig, EventDispatcherInterface $dispatcher): RedirectResponse|Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($article);
            $this->entityManager->flush();

            $event = new ArticleCreateEvent($article);
            $dispatcher->dispatch($event, ArticleCreateEvent::class);

            return $this->redirectToRoute('homepage');
        }

        return new Response($twig->render('article/create.html.twig',
            [
                'article_form' => $form->createView(),
            ]));
    }


    /**
     * @return array|void
     */
    public function getExchangeRates()
    {
        libxml_use_internal_errors(true);
        $dom = new DomDocument;
        $dom->loadHTMLFile("https://www.nbkr.kg/index.jsp?lang=RUS");
        $xpath = new DomXPath($dom);
        $elements = $xpath->query("//div[@id='sticker-exrates']//table/tbody/tr");
        header("Content-type: text/plain");

        if (!is_null($elements)) {
            $arrayWithNodes = [];
            $i = 0;
            foreach ($elements as $element) {

                $nodes = $element->childNodes;
                $arrayWithNodes[$i] = [];
                foreach ($nodes as $node) {
                    if (!trim($node->nodeValue)) {
                        continue;
                    }
                    $arrayWithNodes[$i][] .= trim($node->nodeValue);
                }
                $i++;
            }

            $result = [];
            foreach ($arrayWithNodes as $item) {
                $result[] = implode(',', $item);
            }

            return $result;
        }
    }
}

templates/article/create.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <h1>Create article</h1>

        {{ form(article_form) }}

{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}All articles{% endblock %}

{% block exchange %}


    <ul class="list-group list-group-flush col-2 position-absolute" style="width: 250px">
        <h4>Exchange rates:</h4>
        {% for value in exchange_rates %}
            <li class="list-group-item">{{ value }}</li>
        {% endfor %}
    </ul>

{% endblock %}

{% block body %}
    <h1 class="mt-2">All articles:</h1>

    <a class="btn btn-outline-info my-2" href="{{ path('article.create') }}">Add new article</a>

    {% if articles|length > 0 %}

    <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for article in articles %}
            <div class="col">
                <div class="card h-75">
                    <img src="{{ asset('uploads/' ~ article.image) }}" class="card-img-top h-75" alt="{{ asset('uploads/' ~ article.image) }}">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{{ path('article.show', {id:article.id}) }}">{{ article.title }}</a>
                        </h5>
                        <p class="card-text">{{ article.body }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Published at: {{ article.publishAt|format_datetime('medium', 'short') }}</small>
                    </div>
                </div>
            </div>
    {% endfor %}
    </div>

    {% else %}
        <p>No articles.</p>
    {% endif %}

{% endblock %}

templates/article/show.html.twig
{% extends "base.html.twig" %}

{% block body %}

    <h1>{{ article.title }}</h1>

    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ asset('uploads/' ~ article.image) }}" class="img-fluid rounded-start" alt="{{ asset('uploads/' ~ article.image) }}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <p class="card-text">{{ article.body }}</p>
                    <p class="card-text"><small class="text-muted">Published at: {{ article.publishAt|format_datetime('medium', 'short') }}</small></p>
                </div>
            </div>
        </div>
    </div>

    <a class="btn btn-outline-dark" href="{{ path('homepage') }}">Go back</a>

{% endblock %}